### PR TITLE
Feature: Blog Subscription Styles and States

### PR DESCRIPTION
**Pull request by dkullmann**
@dkullmann @sborrazas :

Here's the styles for the blog subscription module: http://cl.ly/image/2z1I1p3j321S, and here the PSDs so you can grab the styles: http://cl.ly/0X302338380K.

Maybe we can do a little animation when the success or error states appear, what do you think?

### CODE REVIEW

**Comment by dkullmann** [comment]
image
image

by adding ``interest: ruby``` to your pages front-matter a subscription link for the interest will appear. The possible interests are:
* ruby
* python
* design

If your page doesn't declare an interest then this form won't show up.

**Comment by dkullmann** [comment]
I think we should consider adding "frontend" and "ios" or "mobile"

I don't want to have too many different areas, so maybe "frontend" can just fall into "ruby" for now since that's the most popular language.

**Comment by charlitoss** [comment]
@dkullmann i think by interest you are referring to the typical blog categories, and yes we can have a few global categories like: design, frontend, engineering and misc/general.

**Comment by sborrazas** [comment]
I don't think we need to add some filter to the blogposts subscription. I don't think there will be that many posts anyway.

**Comment by dkullmann** [comment]
@sborrazas 

> I don't think there will be that many posts anyway.

I think this will be an important component of our company and that we can/should continue to update it regularly. There will be many posts.

> I don't think we need to add some filter to the blogposts subscription

If you are a ruby developer you don't want to get emails about design tips and visa versa. We should have interest-based groupings so we don't spam people when we post new articles.

**Comment by sborrazas** [comment]
Looks good to me then. :unlock:

**Comment by dkullmann** [comment]
Thanks @sborrazas

**Pull request merged**
